import { createContext, useContext, useMemo, type ReactNode } from 'react';
import type { CategoryId } from '../types';

export const languageIds = ['en', 'fr', 'id'] as const;
export type LanguageId = (typeof languageIds)[number];

export const languages: Array<{ id: LanguageId; label: string }> = [
  { id: 'en', label: 'English' },
  { id: 'fr', label: 'Français' },
  { id: 'id', label: 'Bahasa Indonesia' }
];

const fr: Record<string, string> = {
  'Search the web': 'Rechercher sur le web', 'Search the web for {title}': 'Rechercher « {title} » sur le web',
  'Your collections': 'Vos collections', 'Local & private': 'Local et privé', 'Your ratings stay on this device': 'Vos classements restent sur cet appareil',
  'Settings': 'Paramètres', 'How ranking works': 'Comment fonctionne le classement', 'Close navigation': 'Fermer la navigation', 'Primary navigation': 'Navigation principale',
  'Ranking guide': 'Guide du classement', 'Choose between two works': 'Choisissez entre deux œuvres', 'Each duel asks which work you prefer. There are no scores to invent and you can undo the last choice.': 'Chaque duel vous demande quelle œuvre vous préférez. Aucune note à inventer, et le dernier choix peut être annulé.', 'Elo updates the order': 'Elo met à jour l’ordre', 'Beating a highly rated work produces a larger change. Expected results make smaller adjustments.': 'Battre une œuvre très bien classée produit un changement plus important. Un résultat attendu entraîne un ajustement plus faible.', 'New items move quickly': 'Les nouveaux éléments évoluent rapidement', 'Fast-track gives new items larger rating changes. After enough comparisons, their movement becomes steadier.': 'Le placement accéléré applique de plus grands changements aux nouveaux éléments. Après suffisamment de comparaisons, leur évolution se stabilise.', 'You stay in control': 'Vous gardez le contrôle', 'Start a general duel or open one item and make it compete directly. Filters never change the underlying ranking.': 'Lancez un duel général ou ouvrez un élément pour le faire concourir directement. Les filtres ne modifient jamais le classement réel.', 'Got it': 'Compris',
  'Your ladder starts here': 'Votre classement commence ici', 'Add at least two things, then let your choices sort out the order.': 'Ajoutez au moins deux éléments, puis laissez vos choix déterminer leur ordre.', 'Add your first item': 'Ajouter votre premier élément', 'Title is required.': 'Le titre est obligatoire.',
  'Rank': 'Rang', 'Work': 'Œuvre', 'Details': 'Détails', 'Record': 'Bilan', 'Rating': 'Classement', 'Year unknown': 'Année inconnue', 'Unclassified': 'Non classé', 'placing': 'placement', 'Leader': 'En tête',
  'Back to ladder': 'Retour au classement', 'Head to head': 'Face-à-face', 'Which stays with you?': 'Laquelle vous accompagne ?', 'Trust the instinct. You can always change the order later.': 'Fiez-vous à votre instinct. Vous pourrez toujours modifier l’ordre ensuite.',
  'Choose this one': 'Choisir celui-ci', 'or': 'ou', 'Skip pairing': 'Passer ce duel', 'Undo last choice': 'Annuler le dernier choix', 'left': 'gauche', 'right': 'droite', 'exit': 'quitter',
  'Cover preview': 'Aperçu de la couverture', 'Cover image address': 'Adresse de l’image', 'Preparing…': 'Préparation…', 'Choose local image': 'Choisir une image locale', 'Remove': 'Supprimer', 'Local images are resized, stored privately, and included in backups.': 'Les images locales sont redimensionnées, stockées en privé et incluses dans les sauvegardes.', 'The image could not be read.': 'Impossible de lire cette image.',
  'Close details': 'Fermer les détails', 'Elo rating': 'Classement Elo', 'record': 'bilan', 'Fast-track active': 'Placement accéléré actif', 'more choices to settle its position.': 'choix supplémentaires pour stabiliser sa position.',
  'Genre': 'Genre', 'Series / movement': 'Série / mouvement', 'Comparisons': 'Comparaisons', 'Added': 'Ajouté', 'Not set': 'Non renseigné', 'Notes': 'Notes', 'Personal note': 'Note personnelle', 'Manage this item': 'Gérer cet élément', 'More actions': 'Plus d’actions', 'Remove {title} from the collection?': 'Retirer « {title} » de la collection ?', 'Edit details': 'Modifier les détails', 'Save cover': 'Enregistrer l’image', 'Cancel': 'Annuler', 'Change cover': 'Changer l’image', 'Add cover': 'Ajouter une image', 'Make this item compete': 'Faire concourir cet élément', 'Remove from collection': 'Retirer de la collection',
  'Edit': 'Modifier', 'Update the details': 'Modifier les informations', 'Close editor': 'Fermer l’éditeur', 'Start typing to choose an existing value, or finish typing to create a new one. Press Enter or Tab to advance.': 'Commencez à saisir pour choisir une valeur existante, ou terminez la saisie pour en créer une nouvelle. Appuyez sur Entrée ou Tab pour avancer.',
  'Title': 'Titre', 'required': 'obligatoire', 'Creator': 'Créateur', 'Year': 'Année', 'Genre / type': 'Genre / type', 'Comma-separated': 'Séparés par des virgules', 'Add a genre or type': 'Ajouter un genre ou un type', 'Country': 'Pays', 'Add a country': 'Ajouter un pays', 'All countries': 'Tous les pays', 'Series / collection': 'Série / collection', 'Artistic movement': 'Mouvement artistique', 'Type to reuse an existing value': 'Tapez pour réutiliser une valeur existante', 'Type, then press Enter to add': 'Tapez, puis appuyez sur Entrée pour ajouter', 'Why it matters, edition, location…': 'Pourquoi cela compte, édition, lieu…', 'Save changes': 'Enregistrer', 'Writer, artist, or studio': 'Scénariste, dessinateur ou studio',
  'Title and creator are required.': 'Le titre et le créateur sont obligatoires.', 'Could not save these changes. Your previous details are unchanged.': 'Impossible d’enregistrer ces modifications. Les informations précédentes sont inchangées.',
  'Add to': 'Ajouter à', 'Check the details': 'Vérifier les informations', 'Find a': 'Trouver', 'Close': 'Fermer', 'Add method': 'Méthode d’ajout', 'Search catalogue': 'Rechercher dans le catalogue', 'Enter manually': 'Saisir manuellement', 'Search': 'Rechercher',
  'Choose one to fill what the catalogue knows.': 'Choisissez un résultat pour remplir les informations connues du catalogue.', 'Search the catalogue, then select the closest match.': 'Recherchez dans le catalogue, puis sélectionnez le résultat le plus proche.', 'Back to results': 'Retour aux résultats',
  'Required fields are marked. Empty catalogue fields are ready for you—press Enter or Tab to move forward.': 'Les champs obligatoires sont indiqués. Les champs vides sont prêts à être complétés — appuyez sur Entrée ou Tab pour avancer.', 'Category': 'Catégorie', 'Author': 'Auteur', 'Artist, architect, or studio': 'Artiste, architecte ou studio', 'Optional': 'Facultatif', 'New items enter fast-track placement': 'Les nouveaux éléments bénéficient du placement accéléré', 'Add to ladder': 'Ajouter au classement', 'Could not save this item.': 'Impossible d’enregistrer cet élément.',
  'Opening your collection…': 'Ouverture de votre collection…', 'The collection could not be opened.': 'La collection n’a pas pu être ouverte.', 'Your data has not been changed. Try opening it again.': 'Vos données n’ont pas été modifiées. Essayez de l’ouvrir à nouveau.', 'Try again': 'Réessayer', 'Technical details': 'Détails techniques', 'duel': 'duel', 'Start a duel': 'Lancer un duel', 'Add': 'Ajouter', 'Collection summary': 'Résumé de la collection', 'Current favorite': 'Favori actuel', 'Nothing ranked': 'Aucun classement', 'Add an item to begin': 'Ajoutez un élément pour commencer', 'Collection': 'Collection', 'ranked': 'classés', 'Decisions made': 'Décisions prises', 'head-to-head choices': 'choix en face-à-face', 'Fast-track': 'Placement accéléré', 'still finding their place': 'cherchent encore leur place',
  'Statistics': 'Statistiques', 'View ladder': 'Voir le classement', 'Your data': 'Vos données', 'A live view of how your ranking is taking shape.': 'Une vue en direct de la manière dont votre classement prend forme.', 'Based on {count} recorded decisions': 'Basé sur {count} décisions enregistrées', 'Calculating statistics…': 'Calcul des statistiques…', 'Coverage': 'Couverture', 'items compared': 'éléments comparés', 'Average experience': 'Expérience moyenne', 'duels per item': 'duels par élément', 'Settled items': 'Éléments stabilisés', 'with 8 or more duels': 'avec au moins 8 duels', 'Rating evolution': 'Évolution du classement', 'Your current top five across their latest duels': 'Votre top 5 actuel au fil de ses derniers duels', 'Biggest movers': 'Plus fortes évolutions', 'Net change over the latest 50 decisions': 'Évolution nette sur les 50 dernières décisions', 'recent duels': 'duels récents', 'Needs more decisions': 'À départager davantage', 'The least-tested items in this collection': 'Les éléments les moins comparés de cette collection', 'Favorites by classification': 'Favoris par classification', 'Leaders within your genres, series, and movements': 'Leaders de vos genres, séries et mouvements', 'Add genres, series, or movements to see this breakdown.': 'Ajoutez des genres, séries ou mouvements pour afficher cette répartition.', 'Recent decisions': 'Décisions récentes', 'Your latest head-to-head choices': 'Vos derniers choix en face-à-face', 'won against': 'a gagné contre', 'No duel history yet': 'Aucun historique de duel', 'Make a few choices and this dashboard will start revealing patterns.': 'Faites quelques choix et ce tableau de bord commencera à révéler des tendances.',
  'Your ladder': 'Votre classement', 'Ordered by the choices you make, not by scores you invent.': 'Ordonné selon vos choix, pas selon des notes arbitraires.', 'Ratings update after every duel': 'Le classement évolue après chaque duel', 'Period leaders': 'Leaders par période', 'Top by period': 'Top par période', 'Period grouping': 'Regroupement par période', 'Years': 'Années', '5-year spans': 'Périodes de 5 ans', 'Decades': 'Décennies', '{count} ranked': '{count} classés', 'Filter to {period}': 'Filtrer sur {period}', 'Rank within {period}': 'Rang dans {period}', 'Since {year}': 'Depuis {year}', 'Until {year}': 'Jusqu’à {year}', 'Fuzzy search this collection': 'Rechercher dans cette collection', 'Fuzzy search title, creator, series…': 'Rechercher un titre, créateur, série…', 'Filters': 'Filtres', 'Collection view': 'Affichage de la collection', 'Ladder view': 'Vue classement', 'Cover grid view': 'Vue grille de couvertures',
  'Genre, series, or movement': 'Genre, série ou mouvement', 'All classifications': 'Toutes les classifications', 'From year': 'Depuis l’année', 'To year': 'Jusqu’à l’année', 'Any': 'Toutes', 'Clear filters': 'Effacer les filtres', 'Fill details': 'Compléter les informations', 'Fill missing details': 'Compléter les informations manquantes', 'Completion mode': 'Mode archivage', 'Item {current} of {total}': 'Élément {current} sur {total}', 'Exit completion mode': 'Quitter le mode archivage', 'Only missing fields are shown. Press Enter to continue; the last field saves and opens the next item.': 'Seuls les champs manquants sont affichés. Entrée passe au suivant ; le dernier champ enregistre et ouvre l’élément suivant.', 'next field': 'champ suivant', 'skip item': 'passer l’élément', 'Skip item': 'Passer l’élément', 'Save and continue': 'Enregistrer et continuer', 'No missing details in this list.': 'Aucune information manquante dans cette liste.', 'Copy list': 'Copier la liste', '{count} items copied': '{count} éléments copiés', 'Could not copy the list': 'Impossible de copier la liste', 'No matches': 'Aucun résultat', 'Try a broader search or clear your filters.': 'Essayez une recherche plus large ou effacez les filtres.',
  'Last choice undone — choose again': 'Dernier choix annulé — choisissez à nouveau', 'Could not undo that choice': 'Impossible d’annuler ce choix', 'Already added': 'Déjà ajouté', 'added — fast-track active': 'ajouté — placement accéléré actif', 'removed': 'retiré', 'Cover saved for': 'Image enregistrée pour', 'Cover removed from': 'Image supprimée de', 'updated': 'mis à jour', 'moved up': 'a progressé',
  'Appearance': 'Apparence', 'Shortcuts': 'Raccourcis', 'Catalogues': 'Catalogues', 'Data': 'Données', 'Saved automatically': 'Enregistré automatiquement', 'Close settings': 'Fermer les paramètres', 'Language': 'Langue', 'Interface language': 'Langue de l’interface', 'Choose the language used throughout Konomi.': 'Choisissez la langue utilisée dans toute l’interface de Konomi.',
  'Choose your atmosphere': 'Choisissez votre ambiance', 'The content stays the same. Surfaces, text, and interface colors adapt.': 'Le contenu reste identique. Les surfaces, le texte et les couleurs de l’interface s’adaptent.', 'Interface theme': 'Thème de l’interface',
  'Keyboard': 'Clavier', 'Keep your hands home': 'Gardez les mains sur la rangée de repos', 'Click any key to rebind it. Shortcuts pause while you type in a field.': 'Cliquez sur une touche pour la modifier. Les raccourcis sont suspendus pendant la saisie.', 'Ladder': 'Classement', 'Duel': 'Duel', 'Home-row defaults': 'Touches de repos par défaut', 'Restore home-row defaults': 'Restaurer les raccourcis par défaut',
  'External catalogues': 'Catalogues externes', 'Connect your sources': 'Connectez vos sources', 'Credentials stay in this installation. They are never included in backups or repository files.': 'Les identifiants restent dans cette installation. Ils ne sont jamais inclus dans les sauvegardes ni dans le dépôt.', 'Connected': 'Connecté', 'Not connected': 'Non connecté', 'Testing…': 'Test…', 'Save and test': 'Enregistrer et tester', 'Disconnect': 'Déconnecter',
  'Data & backup': 'Données et sauvegarde', 'Your archive belongs to you': 'Vos archives vous appartiennent', 'Create a complete restorable backup or a spreadsheet of your rankings and statistics.': 'Créez une sauvegarde complète restaurable ou un tableur de vos classements et statistiques.', 'Full Konomi backup': 'Sauvegarde complète Konomi', 'Create backup': 'Créer une sauvegarde', 'Statistics spreadsheet': 'Tableur de statistiques', 'Export CSV': 'Exporter en CSV', 'Fill missing countries': 'Compléter les pays manquants', 'Add a first draft from TMDB, Wikidata, and museum records. Existing countries are never replaced.': 'Ajoute un premier jet depuis TMDB, Wikidata et les catalogues de musée. Les pays existants ne sont jamais remplacés.', 'Fill countries': 'Compléter les pays', 'Countries added to {updated} items. {unavailable} had no reliable country data and {failed} requests failed.': 'Pays ajoutés à {updated} éléments. {unavailable} n’avaient aucune donnée fiable et {failed} requêtes ont échoué.', 'Country enrichment failed. Existing data is unchanged.': 'L’enrichissement des pays a échoué. Les données existantes sont inchangées.', 'Restore a backup': 'Restaurer une sauvegarde', 'Choose file': 'Choisir un fichier', 'Import EMDB or Playnite': 'Importer EMDB ou Playnite', 'Choose folder': 'Choisir un dossier', 'Import Playnite Ranker': 'Importer Playnite Ranker', 'Choose JSON': 'Choisir un JSON', 'Keep backup files somewhere outside this computer if the collection matters to you.': 'Conservez vos sauvegardes ailleurs que sur cet ordinateur si cette collection compte pour vous.',
  'Keyboard shortcut': 'Raccourci clavier', 'Listening…': 'En attente…', 'Shortcut already assigned': 'Raccourci déjà attribué', 'Press replacement key…': 'Appuyez sur une touche de remplacement…',
  'Focus fuzzy search': 'Activer la recherche', 'Jump directly to collection search': 'Aller directement à la recherche de la collection', 'Add an item': 'Ajouter un élément', 'Open the manual or catalogue add flow': 'Ouvrir l’ajout manuel ou par catalogue', 'Start comparing the current category': 'Comparer la catégorie actuelle', 'Choose left item': 'Choisir l’élément de gauche', 'Pick the item displayed on the left': 'Choisir l’élément affiché à gauche', 'Choose right item': 'Choisir l’élément de droite', 'Pick the item displayed on the right': 'Choisir l’élément affiché à droite', 'Show a different opponent': 'Afficher un autre adversaire', 'Restore the previous pairing and ratings': 'Restaurer le duel et les classements précédents',
  'Warm paper and gallery ink': 'Papier chaleureux et encre de galerie', 'Storm': 'Tempête', 'Classic': 'Classique', 'Movie and TV metadata, posters, creators, years, genres, and collections.': 'Métadonnées, affiches, créateurs, années, genres et collections pour les films et séries.', 'Video-game artwork, developers, release years, and genres.': 'Images, développeurs, années de sortie et genres pour les jeux vidéo.',
  'Items, Elo ratings, complete duel history, themes, shortcuts, and language in one JSON file.': 'Éléments, classements Elo, historique complet, thèmes, raccourcis et langue dans un seul fichier JSON.', 'Ranks, ratings, records, win rates, genres, and source metadata as CSV.': 'Rangs, classements, bilans, taux de victoire, genres et sources au format CSV.', 'Choose a Konomi JSON backup. You will review its contents before anything changes.': 'Choisissez une sauvegarde JSON Konomi. Son contenu sera présenté avant toute modification.', 'Select one complete export folder. Subfolders are scanned and source files stay untouched.': 'Sélectionnez un dossier d’export complet. Les sous-dossiers seront analysés et les fichiers sources resteront intacts.', 'Restore Elo ratings, records, and duel history from the ranking extension.': 'Restaurer les classements Elo, bilans et duels depuis l’extension.',
  'Press a key for': 'Appuyez sur une touche pour', 'Use any single key. Press Esc to cancel.': 'Utilisez une seule touche. Appuyez sur Échap pour annuler.', 'Press a replacement key for the previous action.': 'Appuyez sur une touche de remplacement pour l’action précédente.', 'Choose another key.': 'Choisissez une autre touche.', 'Tab stays reserved for navigation. Choose another key.': 'Tab reste réservé à la navigation. Choisissez une autre touche.', 'Use one unmodified key.': 'Utilisez une seule touche sans modificateur.',
  'TMDB is connected on this device.': 'TMDB est connecté sur cet appareil.', 'RAWG is connected on this device.': 'RAWG est connecté sur cet appareil.', 'Catalogue credentials are local configuration. Configure them separately on another browser or computer.': 'Les identifiants des catalogues sont une configuration locale. Configurez-les séparément sur chaque navigateur ou ordinateur.', 'Ready to restore': 'Prêt à restaurer', 'items': 'éléments', 'decisions': 'décisions', 'Merge keeps existing records. Replace removes the current archive first.': 'Fusionner conserve les données existantes. Remplacer supprime d’abord les archives actuelles.', 'Merge': 'Fusionner', 'Replace everything': 'Tout remplacer', 'Playnite ranking ready': 'Classement Playnite prêt', 'games': 'jeux', 'unmatched entries': 'entrées sans correspondance', 'Only the current video-game ratings and history will be replaced.': 'Seuls les classements et l’historique actuels des jeux vidéo seront remplacés.', 'Import ranking': 'Importer le classement',
  'Books': 'Livres', 'Book': 'Livre', 'Written worlds': 'Mondes écrits', 'Essays': 'Essais', 'Essay': 'Essai', 'Ideas in form': 'Pensées en forme', 'Comics': 'Bandes dessinées', 'Comic': 'Bande dessinée', 'Sequential art': 'Art séquentiel', 'Movies': 'Films', 'Movie': 'Film', 'On screen': 'À l’écran', 'TV shows': 'Séries TV', 'TV show': 'Série TV', 'In episodes': 'En épisodes', 'Paintings': 'Peintures', 'Painting': 'Peinture', 'On canvas': 'Sur toile', 'Architecture': 'Architecture', 'Building': 'Bâtiment', 'Built form': 'Formes bâties', 'Video games': 'Jeux vidéo', 'Game': 'Jeu', 'Played worlds': 'Mondes joués', 'Songs': 'Chansons', 'Song': 'Chanson', 'One track': 'Un morceau', 'Albums': 'Albums', 'Album': 'Album', 'Full records': 'Disques complets', 'Photographs': 'Photographies', 'Photograph': 'Photographie', 'Captured light': 'Lumière saisie', 'Sculptures': 'Sculptures', 'Sculpture': 'Sculpture', 'Form in space': 'Formes dans l’espace', 'Poems': 'Poèmes', 'Poem': 'Poème', 'Distilled words': 'Mots essentiels'
};

const id: Record<string, string> = {
  'Search the web': 'Cari di web', 'Search the web for {title}': 'Cari “{title}” di web',
  'Your collections': 'Koleksi Anda', 'Local & private': 'Lokal & pribadi', 'Your ratings stay on this device': 'Peringkat Anda tetap di perangkat ini', 'Settings': 'Pengaturan', 'How ranking works': 'Cara kerja peringkat', 'Close navigation': 'Tutup navigasi', 'Primary navigation': 'Navigasi utama',
  'Ranking guide': 'Panduan peringkat', 'Choose between two works': 'Pilih antara dua karya', 'Each duel asks which work you prefer. There are no scores to invent and you can undo the last choice.': 'Setiap duel menanyakan karya mana yang Anda sukai. Tidak ada nilai yang perlu dibuat dan pilihan terakhir dapat dibatalkan.', 'Elo updates the order': 'Elo memperbarui urutan', 'Beating a highly rated work produces a larger change. Expected results make smaller adjustments.': 'Mengalahkan karya berperingkat tinggi menghasilkan perubahan lebih besar. Hasil yang diperkirakan memberi penyesuaian lebih kecil.', 'New items move quickly': 'Item baru bergerak cepat', 'Fast-track gives new items larger rating changes. After enough comparisons, their movement becomes steadier.': 'Penempatan cepat memberi perubahan rating lebih besar pada item baru. Setelah cukup perbandingan, pergerakannya menjadi lebih stabil.', 'You stay in control': 'Anda tetap memegang kendali', 'Start a general duel or open one item and make it compete directly. Filters never change the underlying ranking.': 'Mulai duel umum atau buka satu item dan adukan langsung. Filter tidak pernah mengubah peringkat utama.', 'Got it': 'Mengerti',
  'Your ladder starts here': 'Peringkat Anda dimulai di sini', 'Add at least two things, then let your choices sort out the order.': 'Tambahkan setidaknya dua item, lalu biarkan pilihan Anda menentukan urutannya.', 'Add your first item': 'Tambahkan item pertama',
  'Rank': 'Peringkat', 'Work': 'Karya', 'Details': 'Detail', 'Record': 'Rekor', 'Rating': 'Rating', 'Year unknown': 'Tahun tidak diketahui', 'Unclassified': 'Belum diklasifikasi', 'placing': 'penempatan', 'Leader': 'Teratas',
  'Back to ladder': 'Kembali ke peringkat', 'Head to head': 'Berhadapan', 'Which stays with you?': 'Mana yang paling berkesan?', 'Trust the instinct. You can always change the order later.': 'Percayai insting Anda. Urutannya selalu dapat diubah nanti.', 'Choose this one': 'Pilih ini', 'or': 'atau', 'Skip pairing': 'Lewati pasangan', 'Undo last choice': 'Batalkan pilihan terakhir', 'left': 'kiri', 'right': 'kanan', 'exit': 'keluar',
  'Cover preview': 'Pratinjau sampul', 'Cover image address': 'Alamat gambar sampul', 'Preparing…': 'Menyiapkan…', 'Choose local image': 'Pilih gambar lokal', 'Remove': 'Hapus', 'Local images are resized, stored privately, and included in backups.': 'Gambar lokal diubah ukurannya, disimpan secara pribadi, dan disertakan dalam cadangan.', 'The image could not be read.': 'Gambar tidak dapat dibaca.',
  'Close details': 'Tutup detail', 'Elo rating': 'Rating Elo', 'record': 'rekor', 'Fast-track active': 'Penempatan cepat aktif', 'more choices to settle its position.': 'pilihan lagi untuk menetapkan posisinya.', 'Genre': 'Genre', 'Series / movement': 'Seri / aliran', 'Comparisons': 'Perbandingan', 'Added': 'Ditambahkan', 'Not set': 'Belum diisi', 'Notes': 'Catatan', 'Personal note': 'Catatan pribadi', 'Manage this item': 'Kelola item ini', 'More actions': 'Tindakan lainnya', 'Remove {title} from the collection?': 'Hapus “{title}” dari koleksi?', 'Edit details': 'Edit detail', 'Save cover': 'Simpan sampul', 'Cancel': 'Batal', 'Change cover': 'Ganti sampul', 'Add cover': 'Tambah sampul', 'Make this item compete': 'Adukan item ini', 'Remove from collection': 'Hapus dari koleksi',
  'Edit': 'Edit', 'Update the details': 'Perbarui detail', 'Close editor': 'Tutup editor', 'Start typing to choose an existing value, or finish typing to create a new one. Press Enter or Tab to advance.': 'Mulai mengetik untuk memilih nilai yang ada, atau selesaikan ketikan untuk membuat nilai baru. Tekan Enter atau Tab untuk lanjut.', 'Title': 'Judul', 'required': 'wajib', 'Creator': 'Kreator', 'Year': 'Tahun', 'Genre / type': 'Genre / jenis', 'Comma-separated': 'Pisahkan dengan koma', 'Add a genre or type': 'Tambahkan genre atau jenis', 'Country': 'Negara', 'Add a country': 'Tambahkan negara', 'All countries': 'Semua negara', 'Series / collection': 'Seri / koleksi', 'Artistic movement': 'Aliran seni', 'Type to reuse an existing value': 'Ketik untuk memakai nilai yang sudah ada', 'Type, then press Enter to add': 'Ketik, lalu tekan Enter untuk menambahkan', 'Why it matters, edition, location…': 'Mengapa berarti, edisi, lokasi…', 'Save changes': 'Simpan perubahan', 'Writer, artist, or studio': 'Penulis, ilustrator, atau studio', 'Title and creator are required.': 'Judul dan kreator wajib diisi.', 'Could not save these changes. Your previous details are unchanged.': 'Perubahan tidak dapat disimpan. Detail sebelumnya tidak berubah.',
  'Add to': 'Tambahkan ke', 'Check the details': 'Periksa detail', 'Find a': 'Cari', 'Close': 'Tutup', 'Add method': 'Metode penambahan', 'Search catalogue': 'Cari katalog', 'Enter manually': 'Masukkan manual', 'Search': 'Cari', 'Choose one to fill what the catalogue knows.': 'Pilih satu hasil untuk mengisi informasi dari katalog.', 'Search the catalogue, then select the closest match.': 'Cari katalog, lalu pilih hasil yang paling sesuai.', 'Back to results': 'Kembali ke hasil', 'Required fields are marked. Empty catalogue fields are ready for you—press Enter or Tab to move forward.': 'Kolom wajib telah ditandai. Tekan Enter atau Tab untuk lanjut.', 'Category': 'Kategori', 'Author': 'Penulis', 'Artist, architect, or studio': 'Seniman, arsitek, atau studio', 'Optional': 'Opsional', 'New items enter fast-track placement': 'Item baru masuk penempatan cepat', 'Add to ladder': 'Tambahkan ke peringkat', 'Could not save this item.': 'Item ini tidak dapat disimpan.',
  'Opening your collection…': 'Membuka koleksi Anda…', 'duel': 'duel', 'Start a duel': 'Mulai duel', 'Add': 'Tambah', 'Collection summary': 'Ringkasan koleksi', 'Current favorite': 'Favorit saat ini', 'Nothing ranked': 'Belum ada peringkat', 'Add an item to begin': 'Tambahkan item untuk memulai', 'Collection': 'Koleksi', 'ranked': 'diperingkat', 'Decisions made': 'Keputusan dibuat', 'head-to-head choices': 'pilihan berhadapan', 'Fast-track': 'Penempatan cepat', 'still finding their place': 'masih mencari posisi',
  'Statistics': 'Statistik', 'View ladder': 'Lihat peringkat', 'Your data': 'Data Anda', 'A live view of how your ranking is taking shape.': 'Tampilan langsung tentang bagaimana peringkat Anda terbentuk.', 'Based on {count} recorded decisions': 'Berdasarkan {count} keputusan tersimpan', 'Calculating statistics…': 'Menghitung statistik…', 'Coverage': 'Cakupan', 'items compared': 'item dibandingkan', 'Average experience': 'Pengalaman rata-rata', 'duels per item': 'duel per item', 'Settled items': 'Item stabil', 'with 8 or more duels': 'dengan 8 duel atau lebih', 'Rating evolution': 'Perkembangan rating', 'Your current top five across their latest duels': 'Lima teratas saat ini dalam duel terbaru', 'Biggest movers': 'Perubahan terbesar', 'Net change over the latest 50 decisions': 'Perubahan bersih dari 50 keputusan terakhir', 'recent duels': 'duel terbaru', 'Needs more decisions': 'Perlu lebih banyak keputusan', 'The least-tested items in this collection': 'Item yang paling sedikit diuji dalam koleksi ini', 'Favorites by classification': 'Favorit berdasarkan klasifikasi', 'Leaders within your genres, series, and movements': 'Pemimpin dalam genre, seri, dan aliran Anda', 'Add genres, series, or movements to see this breakdown.': 'Tambahkan genre, seri, atau aliran untuk melihat rincian ini.', 'Recent decisions': 'Keputusan terbaru', 'Your latest head-to-head choices': 'Pilihan berhadapan terbaru Anda', 'won against': 'menang melawan', 'No duel history yet': 'Belum ada riwayat duel', 'Make a few choices and this dashboard will start revealing patterns.': 'Buat beberapa pilihan dan dasbor ini akan mulai menampilkan pola.',
  'Your ladder': 'Peringkat Anda', 'Ordered by the choices you make, not by scores you invent.': 'Diurutkan berdasarkan pilihan Anda, bukan angka buatan.', 'Ratings update after every duel': 'Peringkat diperbarui setelah setiap duel', 'Period leaders': 'Pemimpin periode', 'Top by period': 'Teratas per periode', 'Period grouping': 'Pengelompokan periode', 'Years': 'Tahun', '5-year spans': 'Rentang 5 tahun', 'Decades': 'Dekade', '{count} ranked': '{count} diperingkat', 'Filter to {period}': 'Filter ke {period}', 'Rank within {period}': 'Peringkat dalam {period}', 'Since {year}': 'Sejak {year}', 'Until {year}': 'Sampai {year}', 'Fuzzy search this collection': 'Cari koleksi ini', 'Fuzzy search title, creator, series…': 'Cari judul, kreator, seri…', 'Filters': 'Filter', 'Collection view': 'Tampilan koleksi', 'Ladder view': 'Tampilan peringkat', 'Cover grid view': 'Tampilan kisi sampul', 'Genre, series, or movement': 'Genre, seri, atau aliran', 'All classifications': 'Semua klasifikasi', 'From year': 'Dari tahun', 'To year': 'Sampai tahun', 'Any': 'Semua', 'Clear filters': 'Hapus filter', 'Fill details': 'Lengkapi detail', 'Fill missing details': 'Lengkapi detail yang belum diisi', 'Completion mode': 'Mode pelengkapan', 'Item {current} of {total}': 'Item {current} dari {total}', 'Exit completion mode': 'Keluar dari mode pelengkapan', 'Only missing fields are shown. Press Enter to continue; the last field saves and opens the next item.': 'Hanya kolom yang belum diisi yang ditampilkan. Tekan Enter untuk lanjut; kolom terakhir menyimpan dan membuka item berikutnya.', 'next field': 'kolom berikutnya', 'skip item': 'lewati item', 'Skip item': 'Lewati item', 'Save and continue': 'Simpan dan lanjutkan', 'No missing details in this list.': 'Tidak ada detail yang belum diisi dalam daftar ini.', 'Copy list': 'Salin daftar', '{count} items copied': '{count} item disalin', 'Could not copy the list': 'Tidak dapat menyalin daftar', 'No matches': 'Tidak ada hasil', 'Try a broader search or clear your filters.': 'Coba pencarian yang lebih luas atau hapus filter.',
  'Last choice undone — choose again': 'Pilihan terakhir dibatalkan — pilih lagi', 'Could not undo that choice': 'Pilihan itu tidak dapat dibatalkan', 'Already added': 'Sudah ditambahkan', 'added — fast-track active': 'ditambahkan — penempatan cepat aktif', 'removed': 'dihapus', 'Cover saved for': 'Sampul disimpan untuk', 'Cover removed from': 'Sampul dihapus dari', 'updated': 'diperbarui', 'moved up': 'naik peringkat',
  'Appearance': 'Tampilan', 'Shortcuts': 'Pintasan', 'Catalogues': 'Katalog', 'Data': 'Data', 'Saved automatically': 'Disimpan otomatis', 'Close settings': 'Tutup pengaturan', 'Language': 'Bahasa', 'Interface language': 'Bahasa antarmuka', 'Choose the language used throughout Konomi.': 'Pilih bahasa yang digunakan di seluruh Konomi.', 'Choose your atmosphere': 'Pilih suasana Anda', 'The content stays the same. Surfaces, text, and interface colors adapt.': 'Konten tetap sama. Permukaan, teks, dan warna antarmuka menyesuaikan.', 'Interface theme': 'Tema antarmuka',
  'Keyboard': 'Papan ketik', 'Keep your hands home': 'Tetap di baris utama', 'Click any key to rebind it. Shortcuts pause while you type in a field.': 'Klik tombol untuk mengubahnya. Pintasan berhenti saat Anda mengetik.', 'Ladder': 'Peringkat', 'Duel': 'Duel', 'Home-row defaults': 'Default baris utama', 'Restore home-row defaults': 'Pulihkan pintasan default',
  'External catalogues': 'Katalog eksternal', 'Connect your sources': 'Hubungkan sumber Anda', 'Credentials stay in this installation. They are never included in backups or repository files.': 'Kredensial tetap di instalasi ini dan tidak pernah masuk cadangan atau repositori.', 'Connected': 'Terhubung', 'Not connected': 'Belum terhubung', 'Testing…': 'Menguji…', 'Save and test': 'Simpan dan uji', 'Disconnect': 'Putuskan',
  'Data & backup': 'Data & cadangan', 'Your archive belongs to you': 'Arsip Anda milik Anda', 'Create a complete restorable backup or a spreadsheet of your rankings and statistics.': 'Buat cadangan lengkap atau lembar kerja peringkat dan statistik.', 'Full Konomi backup': 'Cadangan lengkap Konomi', 'Create backup': 'Buat cadangan', 'Statistics spreadsheet': 'Lembar statistik', 'Export CSV': 'Ekspor CSV', 'Fill missing countries': 'Isi negara yang belum ada', 'Add a first draft from TMDB, Wikidata, and museum records. Existing countries are never replaced.': 'Tambahkan draf awal dari TMDB, Wikidata, dan data museum. Negara yang sudah ada tidak akan diganti.', 'Fill countries': 'Isi negara', 'Countries added to {updated} items. {unavailable} had no reliable country data and {failed} requests failed.': 'Negara ditambahkan ke {updated} item. {unavailable} tidak memiliki data tepercaya dan {failed} permintaan gagal.', 'Country enrichment failed. Existing data is unchanged.': 'Pengayaan negara gagal. Data yang ada tidak berubah.', 'Restore a backup': 'Pulihkan cadangan', 'Choose file': 'Pilih berkas', 'Import EMDB or Playnite': 'Impor EMDB atau Playnite', 'Choose folder': 'Pilih folder', 'Import Playnite Ranker': 'Impor Playnite Ranker', 'Choose JSON': 'Pilih JSON', 'Keep backup files somewhere outside this computer if the collection matters to you.': 'Simpan cadangan di luar komputer ini jika koleksi ini penting bagi Anda.',
  'Keyboard shortcut': 'Pintasan papan ketik', 'Listening…': 'Menunggu…', 'Shortcut already assigned': 'Pintasan sudah digunakan', 'Press replacement key…': 'Tekan tombol pengganti…',
  'Focus fuzzy search': 'Fokus pencarian', 'Jump directly to collection search': 'Langsung ke pencarian koleksi', 'Add an item': 'Tambah item', 'Open the manual or catalogue add flow': 'Buka penambahan manual atau katalog', 'Start comparing the current category': 'Mulai membandingkan kategori saat ini', 'Choose left item': 'Pilih item kiri', 'Pick the item displayed on the left': 'Pilih item di sebelah kiri', 'Choose right item': 'Pilih item kanan', 'Pick the item displayed on the right': 'Pilih item di sebelah kanan', 'Show a different opponent': 'Tampilkan lawan lain', 'Restore the previous pairing and ratings': 'Pulihkan pasangan dan rating sebelumnya',
  'Warm paper and gallery ink': 'Kertas hangat dan tinta galeri', 'Storm': 'Badai', 'Classic': 'Klasik', 'Movie and TV metadata, posters, creators, years, genres, and collections.': 'Metadata, poster, kreator, tahun, genre, dan koleksi film serta TV.', 'Video-game artwork, developers, release years, and genres.': 'Gambar, pengembang, tahun rilis, dan genre gim video.',
  'Items, Elo ratings, complete duel history, themes, shortcuts, and language in one JSON file.': 'Item, rating Elo, riwayat duel, tema, pintasan, dan bahasa dalam satu berkas JSON.', 'Ranks, ratings, records, win rates, genres, and source metadata as CSV.': 'Peringkat, rating, rekor, tingkat kemenangan, genre, dan metadata sumber dalam CSV.', 'Choose a Konomi JSON backup. You will review its contents before anything changes.': 'Pilih cadangan JSON Konomi. Isinya akan ditinjau sebelum perubahan dibuat.', 'Select one complete export folder. Subfolders are scanned and source files stay untouched.': 'Pilih satu folder ekspor lengkap. Subfolder dipindai dan berkas sumber tidak diubah.', 'Restore Elo ratings, records, and duel history from the ranking extension.': 'Pulihkan rating Elo, rekor, dan riwayat duel dari ekstensi.',
  'Press a key for': 'Tekan tombol untuk', 'Use any single key. Press Esc to cancel.': 'Gunakan satu tombol. Tekan Esc untuk batal.', 'Press a replacement key for the previous action.': 'Tekan tombol pengganti untuk tindakan sebelumnya.', 'Choose another key.': 'Pilih tombol lain.', 'Tab stays reserved for navigation. Choose another key.': 'Tab tetap digunakan untuk navigasi. Pilih tombol lain.', 'Use one unmodified key.': 'Gunakan satu tombol tanpa pengubah.', 'TMDB is connected on this device.': 'TMDB terhubung di perangkat ini.', 'RAWG is connected on this device.': 'RAWG terhubung di perangkat ini.', 'Catalogue credentials are local configuration. Configure them separately on another browser or computer.': 'Kredensial katalog adalah konfigurasi lokal. Atur secara terpisah di setiap browser atau komputer.', 'Ready to restore': 'Siap dipulihkan', 'items': 'item', 'decisions': 'keputusan', 'Merge keeps existing records. Replace removes the current archive first.': 'Gabungkan mempertahankan data lama. Ganti akan menghapus arsip saat ini.', 'Merge': 'Gabungkan', 'Replace everything': 'Ganti semuanya', 'Playnite ranking ready': 'Peringkat Playnite siap', 'games': 'gim', 'unmatched entries': 'entri tidak cocok', 'Only the current video-game ratings and history will be replaced.': 'Hanya rating dan riwayat gim video saat ini yang akan diganti.', 'Import ranking': 'Impor peringkat',
  'Books': 'Buku', 'Book': 'Buku', 'Written worlds': 'Dunia tertulis', 'Essays': 'Esai', 'Essay': 'Esai', 'Ideas in form': 'Gagasan dalam bentuk', 'Comics': 'Komik', 'Comic': 'Komik', 'Sequential art': 'Seni berurutan', 'Movies': 'Film', 'Movie': 'Film', 'On screen': 'Di layar', 'TV shows': 'Serial TV', 'TV show': 'Serial TV', 'In episodes': 'Dalam episode', 'Paintings': 'Lukisan', 'Painting': 'Lukisan', 'On canvas': 'Di kanvas', 'Architecture': 'Arsitektur', 'Building': 'Bangunan', 'Built form': 'Bentuk terbangun', 'Video games': 'Gim video', 'Game': 'Gim', 'Played worlds': 'Dunia permainan', 'Songs': 'Lagu', 'Song': 'Lagu', 'One track': 'Satu lagu', 'Albums': 'Album', 'Album': 'Album', 'Full records': 'Rekaman penuh', 'Photographs': 'Fotografi', 'Photograph': 'Foto', 'Captured light': 'Cahaya yang tertangkap', 'Sculptures': 'Patung', 'Sculpture': 'Patung', 'Form in space': 'Bentuk dalam ruang', 'Poems': 'Puisi', 'Poem': 'Puisi', 'Distilled words': 'Kata-kata yang disuling'
};

const dictionaries: Record<LanguageId, Record<string, string>> = { en: {}, fr, id };
export type Translator = (key: string, variables?: Record<string, string | number>) => string;

export function translate(language: LanguageId, key: string, variables?: Record<string, string | number>) {
  let value = dictionaries[language][key] ?? key;
  for (const [name, replacement] of Object.entries(variables ?? {})) value = value.replaceAll(`{${name}}`, String(replacement));
  return value;
}

export function useTranslator(language: LanguageId): Translator {
  return useMemo(() => (key: string, variables?: Record<string, string | number>) => translate(language, key, variables), [language]);
}

const I18nContext = createContext<{ language: LanguageId; t: Translator }>({ language: 'en', t: (key) => key });

export function I18nProvider({ language, children }: { language: LanguageId; children: ReactNode }) {
  const t = useTranslator(language);
  return <I18nContext.Provider value={{ language, t }}>{children}</I18nContext.Provider>;
}

export function useI18n() { return useContext(I18nContext); }

export function categoryCopy(category: CategoryId, t: Translator) {
  const english: Record<CategoryId, { label: string; singular: string; eyebrow: string }> = {
    books: { label: 'Books', singular: 'Book', eyebrow: 'Written worlds' }, essays: { label: 'Essays', singular: 'Essay', eyebrow: 'Ideas in form' }, comics: { label: 'Comics', singular: 'Comic', eyebrow: 'Sequential art' }, movies: { label: 'Movies', singular: 'Movie', eyebrow: 'On screen' },
    tv: { label: 'TV shows', singular: 'TV show', eyebrow: 'In episodes' }, paintings: { label: 'Paintings', singular: 'Painting', eyebrow: 'On canvas' },
    architecture: { label: 'Architecture', singular: 'Building', eyebrow: 'Built form' }, games: { label: 'Video games', singular: 'Game', eyebrow: 'Played worlds' },
    songs: { label: 'Songs', singular: 'Song', eyebrow: 'One track' }, albums: { label: 'Albums', singular: 'Album', eyebrow: 'Full records' },
    photographs: { label: 'Photographs', singular: 'Photograph', eyebrow: 'Captured light' }, sculptures: { label: 'Sculptures', singular: 'Sculpture', eyebrow: 'Form in space' },
    poems: { label: 'Poems', singular: 'Poem', eyebrow: 'Distilled words' }
  };
  const copy = english[category];
  return { label: t(copy.label), singular: t(copy.singular), eyebrow: t(copy.eyebrow) };
}

export function localeFor(language: LanguageId) { return language === 'fr' ? 'fr-FR' : language === 'id' ? 'id-ID' : 'en-US'; }
